version: '3.8'

services:
  infernet-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: infernet-web
    ports:
      - "3000:3000"  # Web server port
      - "8080:8080"  # PocketBase port
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POCKETBASE_URL=http://localhost:8080
    volumes:
      - pocketbase_data:/app/pb_data  # Persist PocketBase data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - infernet-network

  # Uncomment to run PocketBase as a separate service instead of embedded
  # pocketbase:
  #   image: ghcr.io/muchobien/pocketbase:latest
  #   container_name: pocketbase
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - pocketbase_data:/pb_data
  #   restart: unless-stopped
  #   networks:
  #     - infernet-network

volumes:
  pocketbase_data:
    driver: local

networks:
  infernet-network:
    driver: bridge
